version: '3.3'

services:

  rmi-server:
    build: .
    <<: &default
      image: ubuntu/java
    container_name: rmi-server
    volumes:
      - ./server:/home/RMI/server
    expose:
      - "1099"
    stdin_open: true
    tty: true

  rmi-client:
    <<: *default
    container_name: rmi-client
    depends_on:
      - rmi-server
    volumes:
      - ./client:/home/RMI/client
    stdin_open: true
    tty: true